name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      
      - name: Install Dependencies
        run: npm install
      
      - name: Install Theme
        run: npm install hexo-theme-reimu --save
      
      - name: Install Live2D
        run: npm install hexo-oh-my-live2d
      
      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: public
          path: public
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to Server via Rsync
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          ./public/ git@${{ secrets.SSH_HOST }}:/www/wwwroot/sanae.crystal1921.fun/